module.exports = {
  bind: require('./src/bind'),
  extend: require('./src/extend'),
  each: require('./src/each'),
  objectEach: require('./src/objectEach'),
  map: require('./src/map'),
  objectMap: require('./src/objectMap'),
  find: require('./src/find'),
  filter: require('./src/filter'),
  pluck: require('./src/pluck'),
  reduce: require('./src/reduce'),
  objectReduce: require('./src/objectReduce'),
  invoke: require('./src/invoke'),
  slice: require('./src/slice'),
  indexOf: require('./src/indexOf'),
  keys: require('./src/keys'),
  isMatch: require('./src/isMatch'),
  matches: require('./src/matches'),
  name: 'slapdash',
  version: '0.4.1'
}
