module.exports = {
  bind: require('./lib/bind'),
  extend: require('./lib/extend'),
  each: require('./lib/each'),
  objectEach: require('./lib/objectEach'),
  map: require('./lib/map'),
  objectMap: require('./lib/objectMap'),
  find: require('./lib/find'),
  filter: require('./lib/filter'),
  pluck: require('./lib/pluck'),
  reduce: require('./lib/reduce'),
  objectReduce: require('./lib/objectReduce'),
  invoke: require('./lib/invoke'),
  without: require('./lib/without'),
  slice: require('./lib/slice'),
  indexOf: require('./lib/indexOf'),
  keys: require('./lib/keys'),
  isMatch: require('./lib/isMatch'),
  matches: require('./lib/matches'),
  name: 'slapdash'
}
