module.exports = {
  assign: require('./assign'),
  bind: require('./bind'),
  debounce: require('./debounce'),
  each: require('./each'),
  every: require('./every'),
  filter: require('./filter'),
  find: require('./find'),
  get: require('./get'),
  identity: require('./identity'),
  index: require('./index'),
  indexOf: require('./indexOf'),
  invoke: require('./invoke'),
  isArray: require('./isArray'),
  isMatch: require('./isMatch'),
  isObject: require('./isObject'),
  keys: require('./keys'),
  map: require('./map'),
  matches: require('./matches'),
  not: require('./not'),
  objectEach: require('./objectEach'),
  objectMap: require('./objectMap'),
  objectReduce: require('./objectReduce'),
  pick: require('./pick'),
  pluck: require('./pluck'),
  reduce: require('./reduce'),
  set: require('./set'),
  slice: require('./slice'),
  some: require('./some'),
  unique: require('./unique'),
  values: require('./values')
}

